### ISSUE TITLE
Remove semantic sorting of colours

### ISSUE THREAD

**Issue by bia** [weaveworks/ui-components#148]
Currently colours are sorted by
- primary
- accent
- status
- and other labels like 'legacy.'

( context : @fbarl and I plan to consolidate all colors used in service-ui, scope, and ui-components into the single theme/weave.js file. }

When all of the colors are together in one file, we might consider a more direct grouping, e.g. : 
- greys
- greens
- blues
- reds

or something else?
cc @jpellizzari

**Comment by fbarl** [comment]
The only group left in our theme palette is `state` which consists of `success` and `warning`. We can probably just rename those to `green500` and `yellow500` and close this issue.
