### ISSUE TITLE
Collapse red variants of theme colors

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#157]
I looked into all the places where we use some variants of red color across `ui-components`, `scope` and `service-ui` repos and here's a summary:

![](https://placehold.it/15/ff4b19/000000?text=+) _accent.orange_
 * Timeline vertical focus bar
 * Snackbar error

![](https://placehold.it/15/c7254e/000000?text=+) _status.error_
 * Error alerts
 * Prometheus Graph error alert
 * Form errors
 * Error messages

![](https://placehold.it/15/ad3131/000000?text=+) _wellRead_
 * Login Google button background

![](https://placehold.it/15/b71c1c/000000?text=+) _thunderbird_
 * Various error messages

![](https://placehold.it/15/8b0000/000000?text=+) _redBerry_
 * Scope selectors pin (e.g. metric selector)

![](https://placehold.it/15/ff0000/000000?text=+) _danger_
 * Failures, errors
 * Billing tooltip?
 * Danger button from the theme

![](https://placehold.it/15/ff7c7c/000000?text=+) _salmon_
 * PromQL dropdown

![](https://placehold.it/15/ef5350/000000?text=+) _burntSiena_
 * Instance trial expired
 * Billing payment error
 * Billing remove (button?)
 * Notifications expandable error

![](https://placehold.it/15/dd4b39/000000?text=+) _punch_
 * Login Google button background

![](https://placehold.it/15/f15d2a/000000?text=+) _flamingo_
 * Landing h3 - probably service error

----

I suggest the following set of actions:

* Merge `flamingo`, `burntSiena`, `danger`, `redBerry`, `thunderbird`, `status.error` and `accent.orange` into one color (might still want to use two different opacity groups).
* Extract `punch` and `wellRead` into a separate _thirdParty_ group of colors that should probably be completely independent of our theme.
* Move `salmon` into _PromQL_ group (that we also decided to address separately/later).

cc @miklosp @bia thoughts?

Reference: http://weaveworks-ui-components.s3-website-us-west-2.amazonaws.com/#/styleguide/colors

**Comment by miklosp** [comment]
@bia it's your call
