### ISSUE TITLE
Collapse yellow variants of theme colors

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#164]
Usage across Weave Cloud:

![](https://placehold.it/15/d4ab27/000000?text=+) _status.warning_
* used semantically cross-app
* should probably be kept

![](https://placehold.it/15/d69e30/000000?text=+) _hokeyPokey_
* StatusDetail partial setup

![](https://placehold.it/15/eee1ba/000000?text=+) _chamois_
* fluxTheme current tag

![](https://placehold.it/15/d2d296/000000?text=+) _winterHazel_
* borders/icons for Banner/Container banners

![](https://placehold.it/15/ffffc8/000000?text=+) _lemonChiffon_
* semitransparent backgrounds for Banner/Container banners

---

I suggest we proceed as following:

* Merge `hokeyPokey` into `status.warning` as that's what it should be semantically
* `chamoise` can be made a semitransparent variant of `status.warning` in that one place where it's used as a Deploy version tag (probably around 30%)
* Both `winterHazel` and `lemonChiffon` are used in warning banners, which should semantically be `status.warning`, so make them a semitransparent version of that color

cc @miklosp

**Comment by miklosp** [comment]
LGTM!
