### ISSUE TITLE
Remove next ten least used theme colors

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#176]
* `#393a34` _armadillo_ - used in code editor text -> move to `#3c3c5b` _gunpowder_, looks better
* `#065f7d` _veniceBlue_ - code editor dropdown -> move to `#037aa9` _turquoise_, looks better
* `#ddddff` _fog_ - page footer link hover -> legacy, can be removed now
* `#fdfdfe` _whisper_ - deploy table header bg hover -> use `#ffffff` _white_ or `#fcfcfc` _alabaster_
* `#d7ecf5` _linkWater_ - scope node details hovered row bg -> use transparent `#00d2ff` _accent.blue_
* `#a0be7e` _olivine_ - scope metric fill color -> legacy, always overriden by JS colors
* `#eeeeff` _titanWhite_ - unread events -> use `#f0f0fa` _whiteLilac_, like Deploy table selected rows
* `#dadaea` _snuff_ - deploy unknown tag -> making it `#dfdfea` _mischka_ is barely noticable diff
* `#e9e9f1` _athensGrayDark_ - scope table mode sidebar bg -> could be made `#eeeef4` _athensGray_
* `#d2d2d8` _mischkaDark_ - deploy table borders -> could probably be made into `#cccccc` _silver_

cc @bia

**Comment by bia** [comment]
As we just discussed, the Deploy table header highlight (`#fdfdfe` _whisper_) is barely visible as it is and should be removed anyways.
