### ISSUE TITLE
Revise status colors

### ISSUE THREAD

**Issue by bia** [weaveworks/ui-components#178]
Now that we've pruned a lot of our palette, our status colors are need of a little love
* `#9a9a9a` _disabled_ 
* `#d4ab27` _warning_ 
* `#38bd93` _success_ 
* `#049cd7` _info_ 
* `#c7254e` _error_ 

@fbarl and I have discussed merging `#037aa9` _turquoise_  into `#049cd7` _info_ because _turquoise_ is AA compliant both as a foreground and background

In accordance with #171, we might switch`#c7254e` _error_ to something like `#AD3131` _wellRead_ which is less purple shifted and AA compliant both as a foreground and background, like _turquoise_.

@LiliC and I have discussed having two different levels of `#d4ab27` _warning_, one lighter yellow and one more orange so that we can avoid using red unless a problem is very serious.

We did voice the concern that these changes might make the status colors no longer seem like a palette group, but I'd like to address that if and when it happens.

**Comment by fbarl** [comment]
This issue has almost been resolved now - see https://github.com/weaveworks/ui-components/issues/148#issuecomment-413875368.

**Comment by fbarl** [comment]
This issue has been fully resolved.
