### ISSUE TITLE
Enforce theme font sizes

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#202]
Although our `weave.js` theme includes some font sizes, they are not used that much across our code - I assume the two main reasons are:

a. There are only 3 sizes to choose from which still doesn't cover a lot of cases
b. Their usage is not enforced (or at least hinted by a warning)

```
fontSizes: {
  normal: '0.875em',
  large: '2em',
  xl: '2.827em',
}
```

I suggest the following:

1. Aggregate all the font sizes used across our app into `theme.fontSizes`
2. Force style linters to accept only variables passed to `font-size` property (like it's done for `z-index`)
3. Use only theme font sizes everywhere
4. _(not part of this issue)_ Start dropping some obsolete/ugly font sizes gradually while slowly converging to our unified design system, like we are currently doing with colors

cc @bia @miklosp @jpellizzari

**Comment by jpellizzari** [comment]
I think we should go with a scale like this to cut down on the available options: `10, 12, 14, 18, 24, 36`. I think that gives us enough variation to get a nice hierarchy if we need it, without allowing for too much customization. The actual values aren't as important as limiting it to 6 or less.

Names (respectively): `tiny, small, normal, large, extra-large, heading`. I was thinking this would communicate some intent.

Ii also propose we build this into the `<Text />` component to make it very simple to follow the font-sizes.

**Comment by bia** [comment]
The [typescale](http://type-scale.com/?size=14&scale=1.414&text=A%20Visual%20Type%20Scale&webfont=Proxima%20Nova&font-family=%27Proxima%20Nova%27%2C%20serif&font-weight=400&font-family-headers=&font-weight-headers=inherit&background-color=white&font-color=%23333) that we discussed on the Design Trello might still be a useful reference.

**Comment by rndstr** [comment]
We should also use either `rem` or `px` IMHO. `em` is too much of a headache if people inadvertently nest font-sizes.

**Comment by miklosp** [comment]
That's what I would recommend:
![image](https://user-images.githubusercontent.com/8489585/39861910-0c859f60-543a-11e8-918b-67a15018bb16.png)

**Comment by miklosp** [comment]
@fbarl the grouping I would recommend is:
tiny, small > tiny
normal > small
large > normal
huge, enormous > large
gigantic > extra large
huge is used very sparingly (big numbers on instance homepage and dashboards)

**Comment by fbarl** [comment]
@jpellizzari @bia @miklosp @miklosp Thanks for all the feedback! I think I managed to consolidate most of your comments:

* Taking the unit to be `px`
* Taking the normal font size to be `16px`
* After playing with the type scale @bia linked, we decided to drop it for now
* I took @jpellizzari's naming suggestions at first but then I felt `heading` is a semantic name, which doesn't really apply to our use cases that well
* I stayed a bit on the conservative side and didn't wanna merge `20px` and `24px` so I kept 7 font sizes for the end:

![image](https://user-images.githubusercontent.com/1216874/39919491-1745c45e-5514-11e8-9bf9-4bd3785ea6ba.png)

**Comment by miklosp** [comment]
I say 20 and 24 are too close together to be meaningful. Be brave and merge them. 😉

**Comment by fbarl** [comment]
> I say 20 and 24 are too close together to be meaningful. Be brave and merge them.

Alright, I'll be brave.

**Comment by bowenli** [comment]
@miklosp @bia We should be using a progression instead of picking and choosing. The 16->22 jump is too large. Sometimes you need a localized header. The Elements of Typographic Style is the de facto standard. 6 7 8 9 10 11 12 14 16 18 21 24 36 48 60 72

**Comment by jpellizzari** [comment]
> 6 7 8 9 10 11 12 14 16 18 21 24 36 48 60 72

Too many choices. That is basically a continuous list of integers. I am cool with adding one more level between 16 and 22, but we need to constrain the choices for consistency.

**Comment by miklosp** [comment]
Let's keep the current 6 variants. @bowenli can you please supply an example where you need something between 16 and 22?

**Comment by bowenli** [comment]
![screen_shot_2018-05-16_at_07_27_27](https://user-images.githubusercontent.com/915421/40123274-b6a746ac-58da-11e8-8308-d7d0deed16d5.png)
![screen_shot_2018-05-16_at_07_27_19](https://user-images.githubusercontent.com/915421/40123282-bb414bcc-58da-11e8-9c3d-4d315c29fbd1.png)
![screen_shot_2018-05-16_at_07_26_57](https://user-images.githubusercontent.com/915421/40123287-bfbe22e2-58da-11e8-8a4e-3b7a062d97a0.png)
![screen_shot_2018-05-16_at_07_26_02](https://user-images.githubusercontent.com/915421/40123312-c77da958-58da-11e8-97b1-30e3a0354384.png)
![screen_shot_2018-05-16_at_07_25_49](https://user-images.githubusercontent.com/915421/40123319-cd974fc4-58da-11e8-9bc9-849e5d9fc9eb.png)

**Comment by bowenli** [comment]
Regardless, we should still be using a ratio scaling factor. http://spencermortensen.com/articles/typographic-scale/
