### ISSUE TITLE
Rename some colors to be more obvious

### ISSUE THREAD

**Issue by bia** [weaveworks/ui-components#218]
Talking with @miklosp, we thought that some of the colors should be given more boring names than the auto-generated ones to make them more legible.

For example, `#5b5b88` _comet_  could be `#5b5b88` _cometPurple_  instead.
It is however not nice that the names become longer. Please post any suggestions.

**Comment by miklosp** [comment]
Just "purple"? Variants could be purple-dark, purple-light, purple-xlight, etc...

**Comment by fbarl** [comment]
Basically addressed by #273, #265 and #259.
