### ISSUE TITLE
Grid columns do not break

### ISSUE THREAD

**Issue by davkal** [weaveworks/ui-components#22]
It would be great if the grid were more responsive, so that the columns would break at a certain point. Currently they just shrink.

**Comment by jpellizzari** [comment]
@davkal A ~~unintended side-effect~~ totally planned out feature to get columns to wrap: Omitting the `<Row />` component.

```javascript
      <Grid>
          {
            times(20, i => (
              <GridColumn key={i} span={1}>
                <div style={{backgroundColor: '#8383ac', height: '200px', width: '100%'}} />
              </GridColumn>
            ))
          }
      </Grid>
```

![screen shot 2017-04-25 at 10 44 36 am](https://cloud.githubusercontent.com/assets/2802257/25399417/384b319e-29a4-11e7-80b1-e0f883a6d185.png)

**Comment by jpellizzari** [comment]
Example added to the docs; closing.
