### ISSUE TITLE
Add loading indicator to timeline

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#229]
Useful to know whether some more content is about to be shown in the timeline (right now it's only deployments, but getting a response from backend can take a while and showing partial information without loader suggests we are showing all the content).

p.s. I was thinking of something like this:

![image](https://user-images.githubusercontent.com/1216874/40616660-2823f2ac-628c-11e8-8064-19d687194067.png)

cc @bia

**Comment by fbarl** [comment]
Another idea @bia suggested was making the timestamp blink instead of adding a new element - will try that one first!

**Comment by bia** [comment]
Just the red line or both timestamp and red line are also worth trying.

**Comment by bia** [comment]
After a discussion (and informed by work like [service-ui/pull/2342](https://github.com/weaveworks/service-ui/pull/2342)), we’ve decided to avoid adding more screen elements to represent loading behaviour, but rather alter existing elements (pulsing, etc.). The [animation work here](https://drive.google.com/drive/folders/1xhP6MOpfTjc6oRlTRxWNdFMegQl1jq-N?usp=sharing) will inform actual loading behaviour of the elements as they come onto the screen.
