### ISSUE TITLE
Get rid of mystic color

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#266]
Currently it's only used in _Page not found_ image in Weave Cloud:

![image](https://user-images.githubusercontent.com/1216874/41540693-f9b0e746-7310-11e8-81cc-489002836739.png)

Perhaps we can replace it with `purple100` there to match the theme better:

![image](https://user-images.githubusercontent.com/1216874/41540728-1069b59e-7311-11e8-9a05-3560f56e9c8c.png)

cc @bia

**Comment by bia** [comment]
SGTM
