### ISSUE TITLE
Gather and rename neutral colors

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#273]
In the spirit of #259 and #265, we should rename neutral colors to `grayXXX` (except _white_ and _black_):

![image](https://user-images.githubusercontent.com/1216874/41606879-00638bbe-73e5-11e8-811b-b83fc6fc7e99.png)

* ![](https://placehold.it/15/9a9a9a/000000?text=+) _status.disabled_ is currently used in only one place in Service UI and it should probably be replaced with ![](https://placehold.it/15/8585ad/000000?text=+) _purple400_ there, so that color can be removed
* It would be nice to add one more shade of gray between ![](https://placehold.it/15/cccccc/000000?text=+) _silver_ and ![](https://placehold.it/15/f4f4f4/000000?text=+) _gallery_ for some Scope backgrounds

**Comment by bia** [comment]
Agree with both of your points.

The status colors themselves might also be renamed when we address them in #178.

**Comment by jml** [comment]
Does this impact the user in any way? How does this relate to #260?

**Comment by fbarl** [comment]
@jml It has a negligible user impact, so I think you can skip it for the report. #260 on the other hand massively reduced the number of shades of grays we use in our app (from 17 down to 6 including black and white).
