### ISSUE TITLE
GraphNode Labels are not align to shapes. 

### ISSUE THREAD

**Issue by visualapps** [weaveworks/ui-components#302]
![screen shot 2018-07-17 at 5 09 03 pm](https://user-images.githubusercontent.com/18216179/42815627-863fbd0a-89e5-11e8-8814-b62a56400cfc.png)

**Comment by fbarl** [comment]
Thanks for opening the issue @visualapps, that's a good catch!

The bug seems to appear only on Safari browsers, on Chrome and Firefox it looks fine.

I'll take a look in any case - would be good to resolve this before using it in Scope :)
