### ISSUE TITLE
Add Modal component

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#311]
A prerequisite for https://github.com/weaveworks/service-ui/issues/2813#issuecomment-405962739 - modal box for inviting team members.

The current `Dialog` component could then be refactored as a wrapper around the new `Modal` component.

**Comment by aaron7** [comment]
What would the difference be between a Dialog and a Modal?

**Comment by fbarl** [comment]
> What would the difference be between a Dialog and a Modal?

`Dialog` would still support passing a list of actions throught props?

Arguably, we might want to drop `Dialog` eventually in favor of `Modal` + user rendered actions, but that goes out of the scope of this issue I think.

**Comment by fbarl** [comment]
p.s. It's probably not to true that adding a `Modal` component is a strict prerequisite for weaveworks/service-ui#2813 (comment), as we could still pull that one off with a `Dialog`, but I think it would make sense to have a more generic `Modal` component out there at everyone's disposal.

**Comment by aaron7** [comment]
If you pass no list of actions to a Dialog, isn't it then a modal? That is what we've done with the recent webhooks work: https://github.com/weaveworks/service-ui/blob/master/client/src/pages/organization/webhooks/page.jsx#L85

Maybe we can keep one component with optional actions?

**Comment by fbarl** [comment]
Point taken :)

I will still go ahead and refactor/extend the `Dialog` component a bit to better accommodate the use case in https://github.com/weaveworks/service-ui/issues/2813, but I guess there is no need for adding a new component.

Closing down the issue.
