### ISSUE TITLE
Remove/re-position icon from validation on Input

### ISSUE THREAD

**Issue by guyfedwards** [weaveworks/ui-components#315]
Currently we show an icon next to the input when there is an error, this results in either, the input changing width to show the icon or, the input having to allow room for where the icon can show.

I would suggest maybe removing the icon or revisiting how we show errors to the user for fields not only in forms, but when used independently as well. Currently the error does not feel particularly tied to the input especially if the icon is removed.

The usecase I came up against is on the signup form where the icon appearing causes a funky alignment:
![image](https://user-images.githubusercontent.com/1794071/43130459-a932325e-8f2e-11e8-91bf-7e0582cf0010.png)

Couple of options are: 
1. remove completely
2. move the error icon inside the input and pad the input. This also allows for a success green tick to be added on valid if desired
![image](https://user-images.githubusercontent.com/1794071/43131479-0ea1a190-8f31-11e8-8ef8-d15a805b52a5.png)

3. move icon with validation message and tie them together something like:
![image](https://user-images.githubusercontent.com/1794071/43131395-d2fbc4b8-8f30-11e8-9700-fcdafd1b3cb8.png)

**Comment by leth** [comment]
Did you and @bia consider inserting a new page after the first login? So the flow would be something like:
1. Signup
 Do oauth, or click link in email
2. First page is a friendly "Welcome to Weave Cloud, help us get to know you!" with the fields
3. After submit you get sent to the normal instances list page

**Comment by bia** [comment]
+1 for option 2

**Comment by ngehani** [comment]
What kind of validation is being done on Name/company formats? What if I just type x in the name field and put "xyzkadfaklfjakdjfdl" in the company name?

**Comment by leth** [comment]
> What kind of validation is being done on Name/company formats? What if I just type x in the name field and put "xyzkadfaklfjakdjfdl" in the company name?

No validation; @Futurile is fine with that.
