### ISSUE TITLE
Remove extra space from top and bottom of dropdown highlight

### ISSUE THREAD

**Issue by bia** [weaveworks/ui-components#325]
There should be space between the groups, but the first and last element should look like : 
![screen-shot-2018-07-25-at-11 46 292](https://user-images.githubusercontent.com/92439/43267066-42b50298-90ed-11e8-8847-f92cd97fa78b.png)

instead of the current : 
![screen shot 2018-07-25 at 11 46 29](https://user-images.githubusercontent.com/92439/43266801-96efa710-90ec-11e8-9cf5-63ae80dd3b16.png)

cc @rndstr @fbarl

**Comment by rndstr** [comment]
what's the reason for leaving the extra margin for group dividers but not beginning and end of container? that doesn't look well balanced for me (maybe my font rendering is a bit off, feel free to post screenshots of yours):
![325-dropdown-whitespace](https://user-images.githubusercontent.com/32963/43277756-d7362986-90bd-11e8-98e2-e26525a90f6c.png)

for comparison, no margin at all:
![325-dropdown-group-nomargin](https://user-images.githubusercontent.com/32963/43278006-a05c246e-90be-11e8-886c-8d23f0630d2b.png)

as it is now:
![325-dropdown-group-margin](https://user-images.githubusercontent.com/32963/43278023-aabea774-90be-11e8-9657-a773d9a4444d.png)

(cc #108)

**Comment by bia** [comment]
You're right, it's strange, and I see the same behaviour as our current one in many other places. Let's just keep it as it is.

![screen shot 2018-07-27 at 15 11 30](https://user-images.githubusercontent.com/92439/43322668-9333b5da-91af-11e8-8a1a-b4cfe756007f.png)
