### ISSUE TITLE
Remove outline from Alert boxes

### ISSUE THREAD

**Issue by bia** [weaveworks/ui-components#356]
Now that we have a 2px border radius, it's no longer necessary to outline the border of the alert boxes.

Current : 
![screen shot 2018-08-24 at 10 40 28](https://user-images.githubusercontent.com/92439/44575331-07a03500-a78c-11e8-9619-7978adaad072.png)

Proposed : 
![screen shot 2018-08-24 at 10 41 20](https://user-images.githubusercontent.com/92439/44575359-1d155f00-a78c-11e8-8012-8e47a4c0b6b9.png)

**Comment by visualapps** [comment]
Alerts box with themes looks good without border but what about default alert box. @bia 

<img width="1311" alt="screen shot 2018-09-17 at 1 35 42 am" src="https://user-images.githubusercontent.com/18216179/45600421-1b049000-ba1a-11e8-99b6-c894c2c3d37f.png">

**Comment by bia** [comment]
White background could be an option, but I would prefer to keep the border radius and transparent background on the default alert box.

<img width="789" alt="screen shot 2018-09-17 at 19 28 04" src="https://user-images.githubusercontent.com/92439/45639329-fa871500-baaf-11e8-94d8-6dcef21ff674.png">
