### ISSUE TITLE
Apply standard spacing across all components

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#424]
Follow-up on #400 - probably it makes sense starting with large sizes down to small ones:

* [ ] `64px` xxl
* [ ] `48px` xl
* [ ] `32px` large
* [ ] `24px` ~base~ medium
* [ ] `16px` ~small~ base
* [ ] `12px` small
* [ ] `8px` xs
* [ ] `4px` ~mini~ xxs

**Comment by bia** [comment]
I would go with `xxs` instead of `mini` to avoid confusion.

**Comment by bia** [comment]
We'll address #324 within the scope of this issue.
cc @guyfedwards

**Comment by rndstr** [comment]
> base

my 2c:  is `base` being used anywhere else? this seems more like a `default` to me. `base` tells me that's the value we are basing all the others on which could be something completely different than the 'usual' value to use.

maybe we can name it `medium` instead to go with the sizing names of the others?

**Comment by rndstr** [comment]
@bia that makes totally sense then, thanks for explaining!

Should we also define them in relation to `base` then instead of hardcoding? https://github.com/weaveworks/ui-components/blob/e019f6c486ca968c7bf43ee3047766c6ab15713b/src/theme/spacings.js#L3-L11
