### ISSUE TITLE
Difficult to see that dropdown can scroll sometimes.

### ISSUE THREAD

**Issue by foot** [weaveworks/ui-components#428]
I thought I'd lost some instances from the instances selector the other day before trying to scroll.

- Easy fix would be to make the max-height a multiple of half an item height so that the last item is always chopped in half. A technique that https://react-select.com/home and others probably use.

**Comment by foot** [comment]
Old v. New

<img width="881" alt="screenshot 2018-11-27 at 09 33 48" src="https://user-images.githubusercontent.com/22008/49068674-9b6c1c00-f227-11e8-8428-f1797a5a0119.png">

**Comment by bia** [comment]
Hmmm - I don't like the idea of things getting chopped in half on purpose, but now that I've tried it on react-select it _is_ compelling. Could mention it in my meeting with @miklosp tonight.

**Comment by miklosp** [comment]
Actually being chopped in half is a good way to show that there is more...
