### ISSUE TITLE
New design of ResourceDial component

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#471]
@bia has made a design update to the `ResourceDial` component:

> because they take up less space and *give a better sense of full vs current* [like in grafana]

##### Old
![image](https://user-images.githubusercontent.com/1216874/56217822-28433500-6064-11e9-88f5-8e89c3318d4a.png)

##### New
![image](https://user-images.githubusercontent.com/1216874/56217870-3a24d800-6064-11e9-83fd-1e96fcfb4897.png)

We should update the component to reflect the new look.

**Comment by bia** [comment]
This `max` label is a placeholder for an absolute maximum number for CPU/Memory usage.
Unless someone addresses [service-ui#2983](https://github.com/weaveworks/service-ui/issues/2983), I will have to add this in a later iteration.
