### ISSUE TITLE
Dropdown and Input have different styles when disabled

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#492]
These two should look more similar:

![image](https://user-images.githubusercontent.com/1216874/68419508-a69b2c00-019a-11ea-91f9-fbe016597e8a.png)
![image](https://user-images.githubusercontent.com/1216874/68419548-b74ba200-019a-11ea-9b12-afc417708377.png)

IMO, the former (`Input`) component looks better when disabled so we can just tweak the styles of `Dropdown` component.

**Comment by skarunakar** [comment]
@fbarl  Is this repo open for PR  from someone outside this organisation.  I am not finding any doc regarding guidelines for contributing to this repository.

**Comment by fbarl** [comment]
Thanks for your interest @skarunakar!

Although this repo is technically public, we haven't spent a lot of effort making it contributor-friendly (yet!), mainly due to 3 factors:

1. As far as I'm aware, no big projects except https://github.com/weaveworks/scope and some closed source Weaveworks repos depend on this repo
2. We've only had some minor external contributions so far, not enough to give us stronger incentive for building support
3. The future usage of this repo within Weaveworks is still somewhat unclear as we don't use it consistently across our projects

However, since you asked, I opened https://github.com/weaveworks/ui-components/issues/495.

If you'd like to take on this issue, here's an outline on how you could start:

1. Fork + clone this repo
2. Go to http://weaveworks-ui-components.s3-website-us-west-2.amazonaws.com/ to see what this repo currently consists of
3. Run `yarn install && yarn start` and go to http://localhost:8080 to see the same page locally (with hot reloading)
4. Make code changes and open a PR that I or someone else will take a look at

I hope that helps! :)

**Comment by skarunakar** [comment]
@fbarl 
I have raised this PR which has fix for this
https://github.com/weaveworks/ui-components/pull/496
Can you please review
