### ISSUE TITLE
Consider making dialog title bigger

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#493]
#### Current

* Dialog padding `16px 24px 24px`
* Title font size: `16px`
* Title font weight: `bold`

![image](https://user-images.githubusercontent.com/1216874/68589710-f0cb2880-048c-11ea-8d46-75ce27e7456c.png)

#### Suggested

![image](https://user-images.githubusercontent.com/1216874/68589684-dee98580-048c-11ea-82a6-442c68e9f67b.png)

* Dialog padding `24px`
* Title font size: ~`24px`~ `22px`
* Title font weight: `normal`

cc @bia

**Comment by bia** [comment]
Thanks @fbarl !
Though I suggested `theme.fontSizes.large`, which is `22px`, not `24px`
