### ISSUE TITLE
Alert: Collapse the <div> on close (or on visible="false")

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/ui-components#50]
At the moment setting `visible="false"` on an Alert just animates its opacity. Most often then not, I think we want the Alert div to go away instead of leaving a blank space on the page.

**Comment by jpellizzari** [comment]
@dlespiau  You always have the option to remove the Alert from the DOM yourself: 

`{showAlert && <Alert />}`

The `visible` prop triggers a fade-in/fade-out animation as well. It is not possible to animate removing an element from the DOM.
