### ISSUE TITLE
Add range selector to Time Travel

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#64]
Prerequisite for bringing Time Travel into the _Monitor_ part of Weave Cloud.

_Current mockup_
![image](https://user-images.githubusercontent.com/1216874/32666889-40454f1a-c639-11e7-8f4f-837232c8e671.png)

cc @bia

**Comment by fbarl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add range selector to Time Travel](https://trello.com/c/ea1QGibg/190-add-range-selector-to-time-travel)

**Comment by bia** [comment]
![171110monitortimehorizon4](https://user-images.githubusercontent.com/92439/32671711-bbc0e5fa-c648-11e7-9087-fca63be8a908.jpg)
![171110monitortimehorizon5](https://user-images.githubusercontent.com/92439/32671712-bbf39716-c648-11e7-9249-dda8bced3bfe.jpg)
I think that  I prefer a dropdown.

**Comment by fbarl** [comment]
> I think that I prefer a dropdown.

I think so too. But could you try pulling `Range:` out of the dropdown and then having `1h -> 1 hour`, `30min -> 30 minutes` etc.. since we can afford longer text now? Just curious how it would look :)

**Comment by bia** [comment]
![171110monitortimehorizon6](https://user-images.githubusercontent.com/92439/32672204-7e8f8e82-c64a-11e7-8171-911757eba7c4.jpg)
![171110monitortimehorizon7](https://user-images.githubusercontent.com/92439/32672205-7eba467c-c64a-11e7-883c-89221b3368dc.jpg)
Beautiful!
The spacing of the full list could be improved.
