### ISSUE TITLE
Add dropdown component

### ISSUE THREAD

**Issue by bowenli** [weaveworks/ui-components#66]
We need a dropdown component for the site. I don't expect this to look identical to the instance selector in the nav, since the top nav has special styling.

Areas of use:

- Service dashboard: [Switching between namespaces.](https://github.com/weaveworks/service-ui/pull/1328)
- Teams: [Selecting a team when creating an instance.](https://github.com/weaveworks/service/issues/601#issuecomment-345014257)
- Future: In notifications config, selecting between email addresses.

**Comment by jpellizzari** [comment]
@bowenli WDYT:
![screen shot 2017-11-16 at 3 27 22 pm](https://user-images.githubusercontent.com/2802257/32921502-b5d59ae8-cae2-11e7-993b-38d5846bb5c3.png)

**Comment by bowenli** [comment]
lgtm
