### ISSUE TITLE
Time Travel: small improvements to the UI

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#71]
Two points from #68 are:

> * See if we settle at the current range intervals: 15min, 30min, 1h, 3h, 6h, 24h
> * Consider alternative wording to live / paused states (and perhaps tweak the styling around it)

cc @bia anything else that comes to your mind?

**Comment by bia** [comment]
Good point.
![playbutton3](https://user-images.githubusercontent.com/92439/33332163-ca7bd220-d463-11e7-8eac-1056dc7ddbf7.png)

**Comment by fbarl** [comment]
Two more points to address:

* Get rid of relative `font-size` in `RangeSelector` component (used to cause problems before)
* Remove remaining FF button outlines (the only one I can spot right now is on the Live Mode button)

**Comment by fbarl** [comment]
I feel a bit sceptical about using icons alone for Live/Paused toggle. In that case:

* Play icon could be interpretted as _play_ and not as _live_ (tooltips would help there but then the question is why resort to tooltips for one word that explains the state)
* Should the icon mark the current state or the state a click would take you to? If we have two icons, that should be a bit clearer but IMO doesn't look that nice visually have two icons squashed one next to another :)

What I think would work best with my taste for actionable buttons/toggles would be one icon followed by a word marking the current status. So taking it as it is now but just adding icons before the word:

* ▻ Live
* || Paused

Just an opinion, don't feel that strongly about it though, but I think for such a simple button we should be able to design it in a way that avoids confusion and makes it clear without user having to look at the context around to understand what's going on.

@bia @rade thoughts?

p.s. Looking at this screenshot, my intuition tells me the play icon should be highlighted if the status says _Live_:
![playbutton2](https://user-images.githubusercontent.com/92439/33178655-37052fb4-d067-11e7-85c1-b0bdd8e1a8f6.png)

**Comment by rade** [comment]
> Play icon could be interpretted as play and not as live

What's the difference.

> Should the icon mark the current state or the state a click would take you to?

It feels like the hundredth time we are having this debate. Last one was in the context of Deploy controls - see weaveworks/service-ui#388.

In this case, the play/pause controls are very widely used, so we should just do what everybody else does.

**Comment by bia** [comment]
>In this case, the play/pause controls are very widely used, so we should just do what everybody else does.

But the image that @fbarl posted is what [everyone else does](https://ux.stackexchange.com/questions/9184/alternates-to-the-play-pause-button). I just also don't find it intuitive and I don't like it.

It would at least help if the icons came before the 'Live' text instead of after.

**Comment by rade** [comment]
> is what everyone else does.

Really? They have _words_ in addition to the controls?

**Comment by bia** [comment]
No, nobody does that.
We need to choose :

• Just words
- - - OR - - -
• Just icons

**Comment by bia** [comment]
I think that I don't like the screenshot that @fbarl posted because the combo of both text and icons is confusing. Let's stick with just icons, as I posted here 20 days ago.

**Comment by bia** [comment]
Concluded with @fbarl that we should try to make the play/pause controls more understandable when they are there alone without text. Here are a few iterations :
![playpausetimeline2](https://user-images.githubusercontent.com/92439/34365352-a51bdfe2-ea8f-11e7-8e45-08a131c7c4b9.png)
![playpausetimeline4](https://user-images.githubusercontent.com/92439/34365362-ad5f0ed6-ea8f-11e7-8f7b-1902fe57dfdf.png)
![playpausetimeline7](https://user-images.githubusercontent.com/92439/34365368-b8a906c0-ea8f-11e7-9efe-d98106cb747c.png)
![playpausetimeline9](https://user-images.githubusercontent.com/92439/34365369-b8c26944-ea8f-11e7-988c-dfdfef8135e7.png)
@rade, @fbarl, thoughts or ideas for improvement?

**Comment by rade** [comment]
The 2nd one looks like both buttons are highlighted, but in different ways. Which is bad.

1 and 3 look the same to me and are both fine.

4 is weird.

**Comment by bia** [comment]
True. I also like number 3 the best. Here's one more idea.
![playpausetimeline10](https://user-images.githubusercontent.com/92439/34381949-11726ad6-eb0c-11e7-9b32-66cdaca4c1bc.png)

**Comment by rade** [comment]
Nah.

**Comment by fbarl** [comment]
Alright, option 3 it is! :)
