### ISSUE TITLE
Dropdown improvements

### ISSUE THREAD

**Issue by rndstr** [weaveworks/ui-components#98]
[Dropdown component](http://weaveworks-ui-components.s3-website-us-west-2.amazonaws.com/#/components/dropdown)

* [x] align border on rhs of control and item list
* [x] make first and last item rounded borders top and bottom, respectively
* [x] since we are cutting off long items, add a title/tooltip that allows you to see the full value
* [x] maybe add hover effect same as for buttons as a hint that it is clickable

**Comment by jpellizzari** [comment]
Nice catch on these. Fixed by #101

**Comment by rndstr** [comment]
@jpellizzari the hover effect doesn't show up for me, is this intentional?

**Comment by jpellizzari** [comment]
@rndstr I only added a `title` prop with the full un-truncated label
